"""initial schema

Revision ID: c1ed2a426223
Revises: 
Create Date: 2026-07-01 12:41:19.344608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1ed2a426223'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('sensor_type', sa.Enum('TEMPERATURE', 'HUMIDITY', 'SMOKE', 'WATER_LEAK', 'DOOR', 'CUSTOM', name='sensortype', native_enum=False, length=20), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensors_tag_name'), 'sensors', ['tag_name'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole', native_enum=False, length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alarm_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('alarm_type', sa.Enum('TEMP_HIGH', 'TEMP_LOW', 'HUMIDITY_HIGH', 'HUMIDITY_LOW', 'SMOKE', 'DOOR_OPEN', 'WATER_LEAK', 'PLC_OFFLINE', 'SENSOR_FAILURE', name='alarmtype', native_enum=False, length=20), nullable=False),
    sa.Column('threshold_value', sa.Float(), nullable=True),
    sa.Column('hysteresis', sa.Float(), nullable=False),
    sa.Column('min_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alarmseverity', native_enum=False, length=10), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('configurations',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.Enum('GOOD', 'BAD', 'STALE', name='readingquality', native_enum=False, length=10), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sensor_readings_sensor_timestamp', 'sensor_readings', ['sensor_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_table('sensor_readings_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_daily_bucket_start'), 'sensor_readings_daily', ['bucket_start'], unique=False)
    op.create_index('ix_sensor_readings_daily_sensor_bucket', 'sensor_readings_daily', ['sensor_id', 'bucket_start'], unique=True)
    op.create_table('sensor_readings_hourly',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('bucket_start', sa.DateTime(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=False),
    sa.Column('max_value', sa.Float(), nullable=False),
    sa.Column('avg_value', sa.Float(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_hourly_bucket_start'), 'sensor_readings_hourly', ['bucket_start'], unique=False)
    op.create_index('ix_sensor_readings_hourly_sensor_bucket', 'sensor_readings_hourly', ['sensor_id', 'bucket_start'], unique=True)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('level', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='loglevel', native_enum=False, length=10), nullable=False),
    sa.Column('category', sa.Enum('PLC_CONNECTION', 'SYSTEM_RESTART', 'AUTH', 'CONFIG_CHANGE', 'BACKUP', name='logcategory', native_enum=False, length=20), nullable=False),
    sa.Column('message', sa.String(length=1000), nullable=False),
    sa.Column('meta', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_table('alarms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.Enum('ACTIVE', 'ACKNOWLEDGED', 'CLEARED', name='alarmstate', native_enum=False, length=15), nullable=False),
    sa.Column('triggered_value', sa.Float(), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.Integer(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('message', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['alarm_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alarms')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index('ix_sensor_readings_hourly_sensor_bucket', table_name='sensor_readings_hourly')
    op.drop_index(op.f('ix_sensor_readings_hourly_bucket_start'), table_name='sensor_readings_hourly')
    op.drop_table('sensor_readings_hourly')
    op.drop_index('ix_sensor_readings_daily_sensor_bucket', table_name='sensor_readings_daily')
    op.drop_index(op.f('ix_sensor_readings_daily_bucket_start'), table_name='sensor_readings_daily')
    op.drop_table('sensor_readings_daily')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index('ix_sensor_readings_sensor_timestamp', table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_table('configurations')
    op.drop_table('alarm_rules')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sensors_tag_name'), table_name='sensors')
    op.drop_table('sensors')
    # ### end Alembic commands ###
